config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :dashboard, only: [:index]
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @events = Event.where(user_id: current_user.id)
    @attendances = Attendance.where(user_id: current_user.id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_event, only: [:edit, :update, :destroy]
  before_action :authorise_user!, only: [:update, :edit, :destroy]
  

  def index
    @events = Event.all
  end

  def show
    @event = Event.includes(attendances:[:user]).find(params[:id])
  end 

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    
    if @event.save 
      redirect_to @event
    else 
      render new 
    end 
  end

  def edit
  end
  
  def update
    if @event.update(event_params)
      redirect_to @event
    else 
      render :edit
    end 
  end
  
  def destroy
    @event.delete

    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :location, :notes)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def authorise_user!
    return true if current_user.id == @event.user_id
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<h3>Welcome <%= current_user.email%></h3>
<%= link_to "edit details", edit_user_registration_path %>

<h2>My events</h2>
<% @events.each do |event|%>
<p> <%= event.name  %> </p>
<% end %>

<h2>My Attendances</h2>
<% @attendances.each do |attendance|%>
<p> <%= attendance.event.name %> </p>
<% end  %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Update event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Current Events</h1>
<% if user_signed_in? %>
  <%= link_to "Add an event", new_event_path%>
  <%= link_to "Dashboard", dashboard_index_path %>
<% end %>

<% @events.each do |event|%>
<p>
  <%= event.name %>
  <%= link_to 'View', event_path(event) %> |
  <% if user_signed_in? && event.user_id == current_user.id %>
    <%= link_to 'Edit', edit_event_path(event) %> |
    <%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</p>
<% end %>

app/views/events/new.html.erb
<h1>Make a new event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<h3><%= @event.location %></h3>
<p><%= @event.notes %></p>

<h2>Attendees</h2>
<ul>
<% @event.attendances.each do |attendance|%>
<li><%= attendance.user.email %></li>
<% end %>
<ul>
<%= link_to 'Back', events_path %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  Welcome, <%= current_user.email%>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>